### ISSUE TITLE
timeline bars way too wide at day resolution on specific dataset

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#142]
I have a test dataset with just a few bins in it and this is what the timeline looks like:

![image](https://user-images.githubusercontent.com/2365298/63045513-82cb9100-be9e-11e9-9fd5-c66ca116bf15.png)

haven't seen this with other small datasets, so I'll need to work to reproduce it.

It also doesn't switch resolution when zooming in. This is likely a backend issue.

**Comment by joefutrelle** [comment]
backend looks OK ...

**Comment by joefutrelle** [comment]
Seeing an error on the backend which may be related to this, in the `generate_time_series` endpoint

```
ifcbdb       | Internal Server Error: /api/test1/time-series/concentration
ifcbdb       | Traceback (most recent call last):
ifcbdb       |   File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
ifcbdb       |     response = get_response(request)
ifcbdb       |   File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
ifcbdb       |     response = self.process_exception_by_middleware(e, request)
ifcbdb       |   File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
ifcbdb       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
ifcbdb       |   File "/ifcbdb/dashboard/views.py", line 437, in generate_time_series
ifcbdb       |     time_start = min(time_data)
ifcbdb       | ValueError: min() arg is an empty sequence
```

**Comment by joefutrelle** [comment]
This error appears to be caused by a bad URL coming from the frontend:

```
/api/test1/time-series/concentration?resolution=auto&start=2018-01-02%2018:00&end=2018-06-15%2006:00
```

There's something wrong with the date formatting.

**Comment by joefutrelle** [comment]
Here's the response payload associated with these too-wide bars; it looks OK.

```json
{"x": ["2017-10-13T00:00:00Z", "2018-09-05T00:00:00Z"], "x-range": {"start": "2017-10-13T00:00:00Z", "end": "2018-09-05T00:00:00Z"}, "y": [374.961145336007, 224.845248656918], "y-axis": "ROIs / ml", "resolution": "day"}
```
